version: "3.3"
services:
  react-app:
    build:
      context: .
      args: 
        DOCKER_USER_ID: ${USER_ID}
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - ./app:/usr/app
    environment: 
      REACT_APP_API_URL: /api
