auth:
  enabled:	false
  username: mongo-user
  database:	contact-sheet

service:
  type: NodePort

volumePermissions:
  enabled: true # If sets to false creating the datadir fails because of permissions

persistence:
    size: 50Gi
