apiVersion: v1
kind: Endpoints
metadata:
  namespace: local
  name: gluster-cluster
subsets:
- addresses:
  - ip: 192.168.1.200
  ports:
  - port: 1
    protocol: TCP
- addresses:
  - ip: 192.168.1.201
  ports:
  - port: 1
    protocol: TCP
- addresses:
  - ip: 192.168.1.203
  ports:
  - port: 1
    protocol: TCP
