apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "contact-sheet.fullname" . }}
  labels:
    {{- include "contact-sheet.labels" . | nindent 4 }}
data:
  storage.json: |
    {
        "storage_list" : [
            {
                "id": "s3_main_storage",
                "type": "AWS_S3",
                "config": {
                    "key" : {
                        "from_env": "AWS_KEY"
                    },
                    "secret" : {
                        "from_env": "AWS_SECRET"
                    },
                    "bucket" : "picture.backup.test"
                }
            }
        ]
    }
