apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "contact-sheet.fullname" . }}
  labels:
    {{- include "contact-sheet.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "contact-sheet.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "contact-sheet.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "contact-sheet.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: storage-config
          configMap:
            name: {{ include "contact-sheet.fullname" . }}
        - name: google-config
          configMap:
            name: {{ include "contact-sheet.fullname" . }}-google
      containers:
        - name: {{ .Chart.Name }}-nginx
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}contact-sheet-nginx:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
        - name: {{ .Chart.Name }}-api
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}contact-sheet-api:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: storage-config
              mountPath: /usr/app/storage.json
              subPath: storage.json
            - name: google-config
              mountPath: /usr/app/google_api_oauth.json
              subPath: google_api_oauth.json
          env:
          - name: AWS_KEY
            valueFrom:
              secretKeyRef:
                name: aws-creds
                key: AWS_KEY
          - name: AWS_SECRET
            valueFrom:
              secretKeyRef:
                name: aws-creds
                key: AWS_SECRET
          - name: HOST
            value: "0.0.0.0"
          - name: MONGO_HOST
            value: "mongodb-local.local"
          - name: DEBUG
            value: "0"
          - name: AWS_BUCKET
            value: "contactsheet.backup.thibault"
          ports:
            - name: http-api
              containerPort: 8000
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /ping
              port: http-api
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
